version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_service
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

volumes:
  pgdata:
