version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_service
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
